adddddddddd

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -48,6 +48,12 @@ jobs:
           url2=$(curl -s https://api.gofile.io/servers | jq -r '.data.servers[0].name')
           [ -z "$url2" ] && url2="store$(( $RANDOM % 8 + 1 ))"
           Linkrom="$(curl -L -N -H "$User" -F "file=@${{ env.rom_path }}" "https://${url2}.gofile.io/contents/uploadFile" | jq -r .data.downloadPage)"
+          
+          # Kiểm tra lỗi và thoát nếu có lỗi
+          if [ -z "$Linkrom" ] || [[ "$Linkrom" == "null" ]]; then
+            echo "Error: Failed to get download link."
+            exit 1
+          fi
 
           echo "Link ROM: $Linkrom"
           touch "${GITHUB_WORKSPACE}/log.txt"
